import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import MainHeader from '../components/MainHeader';
import Button from '../components/common/Button';
import Navigations from '../components/Navigations';
import Carousel from '../components/Carousel';
import TrendingAnime from '../components/TrendingAnime';
import ThrowbackAnime from '../components/ThrowbackAnime';
import { AiFillStar, AiFillCaretRight, AiFillHeart } from "react-icons/ai";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <MainHeader />
        <Carousel />
        <div className={styles.main}>

        {/* <div className={styles.hero}>
          <div className={styles.carousel}>
            <h1 className={styles.title}>
              Kimetsu no Yaiba
            </h1>
            <div className={styles.subheader}>
              <div className={styles.rating}>
                <div className={styles.rate}>
                  <AiFillStar className={styles.icon} size={20} />
                  <span>5.0</span>
                </div>
                <div className={styles.category}>
                  <p>Category: Adventure fiction, Dark fantasy, Martial Arts</p>
                </div>
              </div>
              <p>
                Demon Slayer: Kimetsu no Yaiba is a Japanese manga series written and illustrated by Koyoharu Gotouge. It follows teenage Tanjiro Kamado, who strives to become a demon slayer after his family was slaughtered and his younger sister Nezuko turned into a demon.
              </p>
              <div className={styles.links}>
                <Button className="main mr">
                  <AiFillCaretRight size={20} />
                  Watch Now!
                </Button>
                <Button className="second fixed">
                  <AiFillHeart size={20} />
                </Button>
              </div>
            </div>
            <Navigations />
          </div>
        </div> */}
        <TrendingAnime />
        <ThrowbackAnime />
        </div>
      </main>
    </div>
  )
}
