import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import MainHeader from '../components/MainHeader';
import Button from '../components/common/Button';
import Navigations from '../components/Navigations';
import Carousel from '../components/Carousel';
import TrendingAnime from '../components/TrendingAnime';
import ThrowbackAnime from '../components/ThrowbackAnime';
import { AiFillStar, AiFillCaretRight, AiFillHeart } from "react-icons/ai";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <MainHeader />
        <Carousel />
        <div className={styles.main}>
          <TrendingAnime />
          <ThrowbackAnime />
        </div>
      </main>
    </div>
  )
}
